### PR TITLE
Update WeatherWidget.js

### PR DESCRIPTION
**Pull request by gerard33**
Add Humidity only device

### CODE REVIEW

**Comment by gerard33** [comment]
@t0mg, I made a pull request (or actually 3...) for a Humidity only device which I am using in Domoticz.

Can you have a look at this lines in the WeatherWidget.js
`return { humonly: Number(device.nvalue) + 1, humstat: device.svalue1 };`
`{params.humonly && <div className="humonly">{Number(params.humonly) - 1}</div>}`

I had to do a dirty +1 and -1 because otherwise the widget would not show a value of 0% correctly.
I am using a humidity sensor for a scripts that predicts if it is going to rain (with some data of a Dutch site).
That device is at 0% when there is no change of rain. See the screenshots below (Regen verwacht = rain predicted).

With the +1 -1 trick:
hum_sensor

Without the +1 -1 trick:
hum_sensor2

**Comment by t0mg** [comment]
The test "{params.humonly && " fails when this param's value is zero, because in javascript 0 == false (and "0" == false too). So you need to do something like {typeof params.humonly == "Number" && ... or {params.humonly !== undefined &&...
This makes me realize that I may have made the very same mistake in other places in the code, I need to check...

Also, could you please try to merge your pull requests into one ? 

Thanks for your continuous effort on reacticz!

**Comment by gerard33** [comment]
I will try to change that part of the code :)

Maybe it's best to delete this 3 pull request, so I can make one new pull request?
I am having some issues in updating my fork with your changes. So googling now what should be the best approach.

**Comment by t0mg** [comment]
ok, closing

**Pull request closed without merging**
