### PR TITLE
Add a control to select zoom (smaller/bigger) for the layout

### PR DESCRIPTION
**Pull request by davidlb**
Should fix issue #102

### CODE REVIEW

**Comment by t0mg** [comment]
It's a nice idea :) Unfortunately the scale transform messes up with the grid layout when trying to drag and drop elements (I'm guessing that the pointer position does not take the scale into account). I guess there are a few options: fix react-grid-layout directly in their codebase, or focus on font-size multipliers only, eg adding a global class to the grid and some css rules in the widget (that was the original request so that would be ok).

**Comment by davidlb** [comment]
Argh, you're right, I didn't notice it :(

**Comment by t0mg** [comment]
Thanks for the fix, I'll check it out tonight!

**Comment by t0mg** [comment]
Hello @davidlb , I've converted all the font-sizes to em in commit b02f503, can you pull this in your fork so that we can make sure it works as expected?

Thanks!

**Comment by t0mg** [comment]
Looks good to me! Thanks @davidlb :)

**Pull request merged**
