### PR TITLE
Wind widget

### PR DESCRIPTION
**Pull request by gerard33**
Added a wind widget
Is shows the name in Domoticz, the direction and the windspeed in KM/H

wind

### CODE REVIEW

**Comment by gerard33** [comment]
@t0mg, can you please double check if I implemented the `case = "Wind"` part correctly in DeviceWidget.js?
Not sure if I have to add a `default:
          break;` part, although its working correctly.

And maybe it's an option to use this icon https://material.io/icons/#ic_near_me and rotate it according to the wind direction? But for that to work I will really need your help :)

**Comment by t0mg** [comment]
Haha nice work! OK we should start assigning these issues to ourselves because I was also working on the same widget :) Main differences with mine is that it also supports gust and bearing, and I converted speed to m/s instead of km/h (not sure what's best, I'm no meteorologist). Are bearing and gust useless ?

I also picked the fan icon instead of the explore one (https://material.io/icons/#ic_toys) but I like the idea of using the arrow and rotating it according to the direction. To do that I'd probably do exactly like I did with the AlertWidget colors, using a css class for each case, except that instead of setting a fill property I'd just set a transform.

**Comment by t0mg** [comment]
And yes your case is correct,  the default: break was already there anyway. And if you meant adding a break inside your case, that would be useless. Since you are returning something inside of it, a break statement below that – or anything else for that matter – would be dead code anyway.

**Comment by Sneeuwtijger** [comment]
For the m/s or km/h wind speed in this widget - same with temperature in degrees F or degrees C - is it an idea to have some setting so the user can specify it?

**Comment by t0mg** [comment]
It's a bit of a philosophical question. It's obviously possible to add settings in Reacticz, but the initial goal was to have something very straightforward, without a lot of configuration options. I started this project because I was disappointed that most of the frontpages I found required a lot of manual editing to list idx and device names, even though that stuff was already available in Domoticz. So if unit preferences are not available in Domoticz, then I'd rather go Apple style and just choose whatever unit I think is best for the users :)

**Comment by NietGiftig** [comment]
I think you are right, keep Reacticz simple.
But if it is only about showing bits of information in Reacticz, there is a "in between" solution.
Make in the txt widget a routine that can divide the text into parts.
Lets say, if the txt begins with the magic word 'qyz' 
Take the first part of the txt until a divider for example  '~' and show it on row 1
Do the same for the next 2 lines of text.
The normal user never sees it or has to use it, but the well informed ones can use it for their own benefits.
They only have to fill a txt device in domoticz (Lua etc) with the data divided in rows they want to show in Reacticz 
No further settings in Reacticz required.

**Comment by Sneeuwtijger** [comment]
I like your philosophy and agree to it ;)

**Comment by t0mg** [comment]
@NietGiftig if I understand this correctly, you want a new secret feature in TextWidget with special keywords so that the text can be split in two lines instead of one (as it's currently done)? That's doable. We could also provide a syntax to select an icon so that you can look like an alert, contact, watt, wind, etc widget. Feel free to file an issue for this if you think it's an idea worth pursuing.

**Review by t0mg — COMMENTED** [review]
Do you want me to merge this as-is, or do you want to try replacing the icon with a dynamic arrow first?

**Comment by gerard33** [comment]
Don't you want to use your version with the gust and bearing in it? Otherwise it is fine for me to merge this as-is.

Can you help me with the dynamic arrow? Because I don't know how to do that using the CSS.
We can use the svalue1 which Domoticz sends in the MQTT, to determine the exact position of the arrow (based on 360 degrees). Example -> svalue1:"119.00" is ESE.

And I did the wind speed in km/h in stead of m/s because that gives me a better idea what the actual speed is ;)

**Comment by t0mg** [comment]
I don't care much about gust, and bearing will appear visually when we add the dynamic arrow. I'll merge your pull request now and update the widget afterwards. Thanks!

**Comment by gerard33** [comment]
Great, thanks!

**Comment by t0mg** [comment]
Done in commit 282c2ec ;)

**Comment by gerard33** [comment]
Nice :)

**Pull request merged**
