### PR TITLE
Update Themes.js

### PR DESCRIPTION
**Pull request by NietGiftig**
Themes extended with LightBlue and LightGreen
Not too fancy, just added 2 colors

### CODE REVIEW

**Review by t0mg — CHANGES_REQUESTED** [review]
Thanks! One small request before I merge the pull: can you separate the words Light Blue and Light Green? It should still work and it'll be nicer to read. Cheers!

**Comment by NietGiftig** [comment]
Changed.. I think.
Github is not my thing at the moment

**Comment by t0mg** [comment]
Yes you did :) thank you!

**Comment by t0mg** [comment]
@NietGiftig  actually there's a problem: you used the same color for the background of widgets and for "button on", so in some cases the icons are invisible. Any reason why you didn't leave the background white ?

blue

**Comment by t0mg** [comment]
(restoring white for now)

**Comment by NietGiftig** [comment]
I have a couple of selector buttons, I did not liked the white spaces between the buttons and the white background.
Then I tried with a different kind of blue between the background & button on, but then it became a Christmas tree.
Besides that, I want to see a widget as one square thing, with a white background on a white screen it looks like the title does not belong to the widget .
That's why I chose the same color.
Always the problem with design, different views, different solutions ;-).
I do not mind if you want to change or remove them.
I will keep a separate .js for my own devices.

**Comment by t0mg** [comment]
Having a background for the widgets is perfectly fine (that's why I created the 'background' property after all :)), but it should not be the same color as buttonOn or buttonOff because some icons become invisible (in my screenshot, the energy widget lost its plug icon, and the percent widget is a half-doughnut). If you want to see the grid you could for example use a lighter blue or gray.

**Pull request merged**
