### PR TITLE
Rain gauge

### PR DESCRIPTION
**Pull request by gerard33**
Add rain gauge

rain gauge

rain gauge 2

### CODE REVIEW

**Comment by gerard33** [comment]
Something went wrong with syncing the fork, will make a new pull request

**Comment by t0mg** [comment]
I am amazed by the quantity of sensors you have :)

**Comment by gerard33** [comment]
Haha, well that's about it I think ;)

**Comment by Sneeuwtijger** [comment]
@gerard33 which script do you use in Domoticz to get rain values - bit of topic but nice to know ;)

**Comment by gerard33** [comment]
@Sneeuwtijger I am using this device https://www.weerstationkopen.nl/accessoires-weerstations/homewizard/homewizard-regenmeter-ts906.
And I also have 2 rain gauges with data from Weather Underground and Forecast.io.

**Comment by Sneeuwtijger** [comment]
@gerard33 thx for the info - I am using the rain data from Weather Underground, have to check it to the real conditions, it has not rained when I was awake after I added the widget to the dashboard ;)

**Comment by gerard33** [comment]
@Sneeuwtijger, check also issue #54. I have to wait for some rain as well to see if it's working correctly :)

**Comment by Sneeuwtijger** [comment]
@gerard33 yep, saw #54 later - will put info there if available

**Pull request closed without merging**
