### PR TITLE
Update SwitchSelector.css

### PR DESCRIPTION
**Pull request by gerard33**
Reduce the font-size off the buttons on screens < 1024px so text fits better

### CODE REVIEW

**Comment by gerard33** [comment]
Not sure if this is the best way to do this, so if it's not in line with your CSS styling then just reject this request

**Comment by t0mg** [comment]
What exactly are you fixing here ? Could you maybe show me before/after screenshots ?

**Comment by gerard33** [comment]
The text on the selector switch buttons is a bit big on a phone. This change makes the font-size a bit smaller so more text fits on the button (on screens with a width of < 1024px).

Before
img_4616

After
img_4615

**Comment by t0mg** [comment]
I'm a bit worried that this makes the text rather small. Here are a few suggestions:
- limit the device width in your media query to 736px (iPhone 6 plus)
- use pixels or points to define the font size and make it a bit less small

Some alternatives:
- make rows of selector switches with only 2 buttons so that they can take up more horizontal space 
- use Unicode characters for your button labels, such as ⏸ and ▶ (add a whitespace if Domoticz isn't happy). I just tried it works great except that Pause looks rather ugly, but you could use two vertical bars instead eg. || or ❚❚.

selector_with_unicode_symbols

**Comment by gerard33** [comment]
I can even limit the width to 414, which is the width of the iPhone 7+ (736 is the height, see https://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions). Just tested that with my iPhone 7 which has a width of 375.
I will change the font-size to 16px.

I will use the ❚❚ and ▶ :)
With only 2 buttons I need a lot more switch selectors and a lot more scrolling, so I prefer this change.
Just let me know if you can agree with it.

**Comment by t0mg** [comment]
OK, thanks!

**Pull request merged**
