### PR TITLE
iOS manifest and smoke detector widget

### PR DESCRIPTION
**Pull request by gerard33**
1) Added option to refresh caching for iOS web app.

2) Added smoke detector widget.
Supported smoke detector at the moment
- KD101 smoke detector
smoke_sensor

Other smoke sensors can be added if they have a specific stype value in the Domoticz MQTT.

### CODE REVIEW

**Comment by gerard33** [comment]
I have some Fibaro smoke sensor which are in Domoticz recognized as stype "Switch". So for this type of smoke sensors it is currently not possible to distinguish them from a normal on/off switch.

This is a smoke sensor I have which can be distuingished:
`domoticz/out {
   "Battery" : 255,
   "RSSI" : 6,
   "dtype" : "Security",
   "id" : "173E00",
   "idx" : 170,
   "name" : "Smoke Sensor",
   "nvalue" : 0,
   "stype" : "KD101 smoke detector",
   "switchType" : "On/Off",
   "unit" : 0
}`
And this is the Fibaro smoke sensor I have
`domoticz/out {
   "Battery" : 55,
   "RSSI" : 12,
   "dtype" : "Light/Switch",
   "id" : "00001A29",
   "idx" : 438,
   "name" : "Rookmelder zolder",
   "nvalue" : 0,
   "stype" : "Switch",
   "svalue1" : "0",
   "switchType" : "On/Off",
   "unit" : 1
}`

@t0mg, maybe it's an idea to use the description field in the MQTT message for this.
Check if it contains "smoke sensor" so that it can be added to the smoke sensors in Reacticz.

I am currently on Domoticz v3.5877 (stable) which doesn't support the description field in the MQTT message yet, but I saw it has been added a few months ago.
https://github.com/domoticz/domoticz/commit/b309e99ed7a4f89aca9fd12ca8ee2d9b560754b8

What do you think of it?

**Comment by gerard33** [comment]
Without it I still have caching issues. Not when I open Reacticz from Safari on iOS, but when opening Reacticz from the short cut on the home screen. But that's just as described on e.g. http://stackoverflow.com/questions/8337631/mobile-web-app-not-clearing-cache-properly.

Edit: I added "_test" to the following lines in the manifest.webmanifest file for testing purposes:
`"name": "Reacticz_test",
  "short_name": "Reacticz_test",`

After that I added it to the homescreen on my Android device and the new name is visible. So that still seems to be working.

**Comment by t0mg** [comment]
I can check on Android :)

**Comment by gerard33** [comment]
Just to be sure: see my edited post above.

**Comment by t0mg** [comment]
Ok cool, thanks for checking!

**Comment by t0mg** [comment]
I'll merge this now. I'll try to see if we could generate the ios manifest automatically at build time because there is a risk that we'll forget to update the version number.

Regarding your smoke detector, the description hack could work, but it's rather unintuitive. Does the device information provided by the JSON API contain anything useful?

**Comment by gerard33** [comment]
Just did some final testing with the iOS manifest.
When I update the version number in package.json, it's not visible in the iOS web app. Restarted the app a lot, nothing is happening.

Then I also changed the version number in ios.manifest. If I then open the iOS web app, the first time the new version number is not yet available. But after opening the app for the second time, the new version is visible :)
The fact that you have to open the page 2 times is just as described on the link shared above.

Regarding the smoke detector.
Unfortunately the JSON output does not help us there as well:
`{
   "ActTime" : 1486858655,
   "ServerTime" : "2017-02-12 01:17:35",
   "Sunrise" : "07:58",
   "Sunset" : "17:41",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 55,
         "CustomImage" : 141,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 10,
         "HardwareName" : "ZWave",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00001A29",
         "Image" : "smoke_sensor",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-02-05 03:04:43",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Smoke Sensor",
         "Notifications" : "true",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "438"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}`

**Comment by gerard33** [comment]
Just found out that the "Add to desktop" function is part of Chrome on my Windows 7 PC as well.

Another confirmation that the manifest.webmanifest is still being read :-)

chrome

**Pull request merged**
