### PR TITLE
Added some more devices

### PR DESCRIPTION
**Pull request by gerard33**
Added the following devices
- UV Index ("WU - UV straling" in screenshots below)
- Visibility ("WU - zicht")
- Solor Radiation ("FC - Zonnestraling")
- Motion Detector ("Bewegingssensor")
- Lux Sensor ("Bewegingssensor Lux")

weatherinfo
motion_on
motion_off
luxsensor

Used icons from materialdesignicons.com for these devices.
Changed the icons from temp, hum and rain gauge to materialdesignicons.com as well.

Added comments to index.html on the svg's used from materialdesignicons.com.

### CODE REVIEW

**Comment by t0mg** [comment]
Wow! You've been busy! Thank you for your work :)

**Comment by t0mg** [comment]
We'll need another major update on the wiki page :) It's getting rather messy, I think I'll try to turn it into a table instead of that long flat list.

**Comment by felix63** [comment]
Great additions..!

**Comment by t0mg** [comment]
Thanks for updating the wiki @gerard33 !

**Comment by gerard33** [comment]
You're welcome :)

**Pull request merged**
